<?php

use Illuminate\Database\Seeder;

class TypeWordTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $list = [["word_id" => 1, "type_id" => 2],
        ["word_id" => 2, "type_id" => 2],
        ["word_id" => 3, "type_id" => 2],
        ["word_id" => 4, "type_id" => 2],
        ["word_id" => 5, "type_id" => 2],
        ["word_id" => 6, "type_id" => 2],
        ["word_id" => 7, "type_id" => 2],
        ["word_id" => 8, "type_id" => 2],
        ["word_id" => 9, "type_id" => 2],
        ["word_id" => 10, "type_id" => 2],
        ["word_id" => 11, "type_id" => 2],
        ["word_id" => 12, "type_id" => 2],
        ["word_id" => 13, "type_id" => 2],
        ["word_id" => 14, "type_id" => 2],
        ["word_id" => 15, "type_id" => 2],
        ["word_id" => 16, "type_id" => 2],
        ["word_id" => 17, "type_id" => 2],
        ["word_id" => 18, "type_id" => 2],
        ["word_id" => 19, "type_id" => 2],
        ["word_id" => 20, "type_id" => 2],
        ["word_id" => 21, "type_id" => 2],
        ["word_id" => 22, "type_id" => 2],
        ["word_id" => 23, "type_id" => 2],
        ["word_id" => 24, "type_id" => 2],
        ["word_id" => 25, "type_id" => 2],

        ["word_id" => 39, "type_id" => 3],
        ["word_id" => 40, "type_id" => 3],
        ["word_id" => 4, "type_id" => 3],
        ["word_id" => 26, "type_id" => 3],
        ["word_id" => 11, "type_id" => 3],
        ["word_id" => 12, "type_id" => 3],
        ["word_id" => 30, "type_id" => 3],
        ["word_id" => 32, "type_id" => 3],
        ["word_id" => 3, "type_id" => 3],
        ["word_id" => 18, "type_id" => 3],
        ["word_id" => 36, "type_id" => 3],
        ["word_id" => 41, "type_id" => 3],
        ["word_id" => 15, "type_id" => 3],
        ["word_id" => 16, "type_id" => 3],
        ["word_id" => 17, "type_id" => 3],
        ["word_id" => 34, "type_id" => 3],
        ["word_id" => 33, "type_id" => 3],
        ["word_id" => 1, "type_id" => 3],
        ["word_id" => 43, "type_id" => 3],
        ["word_id" => 45, "type_id" => 3],
        ["word_id" => 13, "type_id" => 3],
        ["word_id" => 48, "type_id" => 3],
        ["word_id" => 29, "type_id" => 3],
        ["word_id" => 42, "type_id" => 3],
        ["word_id" => 44, "type_id" => 3],
        ["word_id" => 31, "type_id" => 3],
        ["word_id" => 37, "type_id" => 3],
        ["word_id" => 2, "type_id" => 3],
        ["word_id" => 28, "type_id" => 3],
        ["word_id" => 46, "type_id" => 3],
        ["word_id" => 49, "type_id" => 3],
        ["word_id" => 47, "type_id" => 3],
        ["word_id" => 35, "type_id" => 3],

        ["word_id" => 49, "type_id" => 14],
        ["word_id" => 31, "type_id" => 14],
        ["word_id" => 28, "type_id" => 14],
        ["word_id" => 29, "type_id" => 14],
        ["word_id" => 30, "type_id" => 14],
        ["word_id" => 26, "type_id" => 14],
        ["word_id" => 33, "type_id" => 14],
        ["word_id" => 34, "type_id" => 14],
        ["word_id" => 36, "type_id" => 14],
        ["word_id" => 37, "type_id" => 14],
        ["word_id" => 39, "type_id" => 14],
        ["word_id" => 40, "type_id" => 14],
        ["word_id" => 41, "type_id" => 14],
        ["word_id" => 42, "type_id" => 14],
        ["word_id" => 43, "type_id" => 14],
        ["word_id" => 44, "type_id" => 14],
        ["word_id" => 45, "type_id" => 14],
        ["word_id" => 46, "type_id" => 14],
        ["word_id" => 47, "type_id" => 14],
        ["word_id" => 27, "type_id" => 14],
        ["word_id" => 38, "type_id" => 14],
        ["word_id" => 50, "type_id" => 14],
        ["word_id" => 51, "type_id" => 14],
        ["word_id" => 52, "type_id" => 14],

        ["word_id" => 52, "type_id" => 15],
        ["word_id" => 53, "type_id" => 15],
        ["word_id" => 51, "type_id" => 15],
        ["word_id" => 55, "type_id" => 15],
        ["word_id" => 57, "type_id" => 15],
        ["word_id" => 50, "type_id" => 15],
        ["word_id" => 56, "type_id" => 15],
        ["word_id" => 5, "type_id" => 15],
        ["word_id" => 54, "type_id" => 15],
        ["word_id" => 58, "type_id" => 15],
        
        ["word_id" => 59, "type_id" => 16],
        ["word_id" => 60, "type_id" => 16],
        ["word_id" => 61, "type_id" => 16],
        ["word_id" => 62, "type_id" => 16],
        ["word_id" => 63, "type_id" => 16],
        ["word_id" => 64, "type_id" => 16],
        ["word_id" => 65, "type_id" => 16],
        ["word_id" => 66, "type_id" => 16],
        ["word_id" => 48, "type_id" => 16],
        ["word_id" => 105, "type_id" => 16],
        
        ["word_id" => 73, "type_id" => 17],
        ["word_id" => 80, "type_id" => 17],
        ["word_id" => 81, "type_id" => 17],
        ["word_id" => 82, "type_id" => 17],
        ["word_id" => 84, "type_id" => 17],
        ["word_id" => 85, "type_id" => 17],
        ["word_id" => 74, "type_id" => 17],
        ["word_id" => 75, "type_id" => 17],
        ["word_id" => 67, "type_id" => 17],
        ["word_id" => 9, "type_id" => 17],
        ["word_id" => 68, "type_id" => 17],
        ["word_id" => 86, "type_id" => 17],
        ["word_id" => 69, "type_id" => 17],
        ["word_id" => 8, "type_id" => 17],
        ["word_id" => 70, "type_id" => 17],
        ["word_id" => 83, "type_id" => 17],
        ["word_id" => 7, "type_id" => 17],
        ["word_id" => 76, "type_id" => 17],
        ["word_id" => 14, "type_id" => 17],
        ["word_id" => 77, "type_id" => 17],
        ["word_id" => 78, "type_id" => 17],
        ["word_id" => 71, "type_id" => 17],
        ["word_id" => 6, "type_id" => 17],
        ["word_id" => 79, "type_id" => 17],
        ["word_id" => 72, "type_id" => 17],
        ["word_id" => 87, "type_id" => 17],

        ["word_id" => 73, "type_id" => 18],
        ["word_id" => 76, "type_id" => 18],
        ["word_id" => 78, "type_id" => 18],
        ["word_id" => 75, "type_id" => 18],
        ["word_id" => 77, "type_id" => 18],
        ["word_id" => 88, "type_id" => 18],
        ["word_id" => 89, "type_id" => 18],
        ["word_id" => 90, "type_id" => 18],
        ["word_id" => 91, "type_id" => 18],
        ["word_id" => 92, "type_id" => 18],
        ["word_id" => 93, "type_id" => 18],
        ["word_id" => 94, "type_id" => 18],
        ["word_id" => 95, "type_id" => 18],
        ["word_id" => 96, "type_id" => 18],
        ["word_id" => 97, "type_id" => 18],
        ["word_id" => 98, "type_id" => 18],
        ["word_id" => 99, "type_id" => 18],
        ["word_id" => 101, "type_id" => 18],
        ["word_id" => 102, "type_id" => 18],
        ["word_id" => 75, "type_id" => 18],

        ["word_id" => 97, "type_id" => 19],
        ["word_id" => 100, "type_id" => 19],
        ["word_id" => 99, "type_id" => 19],
        ["word_id" => 103, "type_id" => 19],
        ["word_id" => 104, "type_id" => 19],
        ["word_id" => 98, "type_id" => 19],
        ["word_id" => 102, "type_id" => 19],
        ["word_id" => 90, "type_id" => 19],

        ]

        for ($i = 0 ; $i < count($list) ; ++$i) {
      		DB::table('type_word')->insert([
            'word_id' => $list[$i]['word_id'],
            'type_id' => $list[$i]['type_id'],
        ]);
    }
}
